README.md, commands/admin/kill.js, commands/admin/reload.js, commands/fun/ducc.js, commands/fun/mechallenge.js, commands/fun/piggo.js, commands/info/cross.js, commands/info/graphic.js, commands/info/invite.js, commands/info/members.js, commands/info/mttot.js, commands/info/ranks.js, commands/info/roleinfo.js, commands/sentry/incdata.js, commands/sentry/incursion.js, commands/sentry/initializeembed.js, commands/sentry/removefield.js, commands/sentry/repair.js, commands/sentry/repairscomplete.js, commands/sentry/resetembed.js, commands/sentry/updatefield.js, commands/wiki/builds.js, commands/wiki/nhss.js, index.js
Cleaned up index.js and removed the redundant `restricted` command flag.
Incursion embed is now fully ready for deployment
=> Cleaning up the code

commands/admin/backup.js, db/index.js
admin\backup.js
- creates a "-backup" command to create a backup of user's ID and ID's of the roles they have.
db\index.js changes
- added the takeBackup function
- this does a backup + update old roles if they change(currently only looking for more roles than the backed up version)
- returns the number of changes in the form of an array.
Backup table looks like this in POSTRGRESQL:
users(
id text,
roles text[],
)
=> Backups framework & command

commands/admin/backup.js, commands/admin/getbackup.js, db/index.js, discord/getSortedRoleIDs.js
Table Schema has changed to:
```
users(
id text,
roles text[],
last_saved bigint
);
```
-------------------------------------------------------------------------------
db\index.js
- getSortedRoleID: 
- - Function to get an object of rolePositions, roleIDs and roleNames as an object.
- - Role positions are reversed for better syncing with how it looks on discord.
- getBackup
- - Added a new function getBackup for getbackup command.
- - Updated getBackup for the timestamp data
- - getBackup now returns roles and timestamp data.
- takeBackup
- - Updated takeBackup for the timestamp data.
- - takeBackup now takes the unix epoch value of message creation as input.
commands\admin\getbackup.js
- Gets the backed up data of a user.
- If user isn't found, it returns an empty embed saying so.
- …
=> Backup Changes

commands/fun/zen.js, config.json
A PR to test the development road. The 'zen' command gets you a random quote from https://zenquotes.io
I want to see if this works, before I add all the code from the AXI BGS Sherrif bot (aka Robocop).
... and it's fun too :D
=> added zen command

commands/fun/8ball.js, commands/fun/malda.js
=> new commands 8ball and malda

commands/fun/nuts.js, commands/info/deciat.js
/deciat for the deciat embed and /nuts for Hella
=> Adding an Embed and a fun command

commands/fun/bee.js
add a command for bee because why not
=> bee command

commands/info/graphdata.json, commands/info/pg.js, commands/info/rtfm.js
Adding info/rtfm.js to get a link to the AXI wiki.
Adding info/pg.js to get an embed with information on how to join the AXI PG. 
Updating info/graphdatra.json to include the fss trick image link.
=> Adding /rtfm, /pg and updating graphdata.json

commands/info/mbooni.js
Adds a command which gives info about where to obtain pre-engineered AX weapons
=> Add mbooni command

commands/fun/malda.js
=> Quick /malda update

commands/info/mbooni.js, commands/info/shields.js
might be why the bot is crashing. who knows
=> Small fixes for shields.js and mbooni.js

commands/info/mbooni.js, commands/info/shields.js
Reverts antixenoinitiative/warden.bot#114
=> Revert "Small fixes for shields.js and mbooni.js"

commands/info/mrp.js, package-lock.json
After much digging, it was a known issue and all that had to be done was updating from the old version of discord.js(14.7(?)) to 14.8. Have done it.
=> Fixed ranks command.

package-lock.json
Reverts antixenoinitiative/warden.bot#131
=> Revert "colorConvert issue fixed"

interaction/submission.js
When the accept button is clicked on the staff channel, the bot gives off a friendly reminder to staff if the member who made the request should have myrm.
=> Speedrun command detects myrm on accept

commands/fun/dadjoke.js, package-lock.json
The command fetches a random dad joke from canihazdadjoke api and sends it, also removed emoji from speedrun command
=> added /dadjoke command

commands/info/wtfamhp.js, commands/interceptorcards/glaive.js, commands/interceptorcards/scythe.js, commands/math/data/weapons.json, commands/wiki/nhss.js, index.js
- new hunter cards
- nhss update
- mttot update
- add dev flag
=> Various updates

README.md
Reverts antixenoinitiative/warden.bot#153
=> Revert "Deleted a bunch of AXI-specific commands"

package-lock.json
Reverts antixenoinitiative/warden.bot#151
=> Revert "Bump undici from 5.21.2 to 5.26.3"

commands/Warden/ax-info/graphdata.json, commands/common/matfarm.js
Improvements to `/matfarm` command and more accurate `exertpercent` graphic.
=> Matfarm and exertpercent improvements

commands/info/engineering.js
switches the /engineering command to point to the rehost
=> Update ED Materials to Elite materials
